name: Builds sftpgo Docker image via nix

on:
  push:
    branches: [ "stable" ]

permissions:
  packages: write

jobs:
  build:
    name: Builds Docker image via nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Installs Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the image
        run: nix build .#default -L

      - name: Loads it into Docker
        run: docker load < result

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Push to Container registry
        run: |
          image_name=$(tar -xOf result manifest.json | jq -r '.[0].RepoTags[0]')
          version_tag=$(echo $image_name | cut -d ':' -f2)

          docker tag $image_name "ghcr.io/${{ github.repository_owner }}/sftpgo-nix:$version_tag"
          docker tag $image_name "ghcr.io/${{ github.repository_owner }}/sftpgo-nix:latest"
          docker push --all-tags ghcr.io/${{ github.repository_owner }}/sftpgo-nix

  dependency-scan:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Generates SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository_owner }}/sftpgo-nix:latest
          format: spdx-json
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"

      - name: Scan SBOM
        id: scan
        uses: anchore/scan-action@v6
        with:
          sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
          output-format: json
          fail-build: false

      - uses: actions/upload-artifact@v4
        with:
          name: output-scan-json
          path: ${{ steps.scan.outputs.json }}
